
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSet;
import java.sql.SQLException;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;

public class Usuario extends javax.swing.JFrame {
   
     public void buscardatosTabla(String Valor){
        Conectar conn = new Conectar();
        conn.conexion();
        DefaultTableModel modelo;
        modelo = new DefaultTableModel();
        modelo.addColumn ("ID");
        modelo.addColumn ("Usuario");
        modelo.addColumn ("Contraseña");
        modelo.addColumn ("Tipo usuario");

        String sql;
        
        if(Valor.equals("")){
        sql= "select id_usuario, Usuario,Contrasenia,id_tipoUsuario from usuario";
        }
        else{
            sql = "select id_usuario, Usuario, Contrasenia,id_tipoUsuario from usuario where  Usuario like '%"+Valor+"%'";
        }
        String[] datos = new String[4];
        com.mysql.jdbc.Statement st;
        
        
        try{
            ResultSet rs = (ResultSet) conn.Consultar(sql);
            while(rs.next()){
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);

            modelo.addRow(datos);
            }
            jTable1.setModel(modelo);
        } catch(SQLException ex){
            java.util.logging.Logger.getLogger(Usuario.class.getName()) .log(java.util.logging.Level.SEVERE,null,ex);
        }
    }
     
    public void mostrardatosTabla(String Valor){
        Conectar conn = new Conectar();
        conn.conexion();
        DefaultTableModel modelo;
        modelo = new DefaultTableModel();
        modelo.addColumn ("ID");
        modelo.addColumn ("Usuario");
        modelo.addColumn ("Contraseña");
        modelo.addColumn ("Tipo usuario");

        String sql;
        
        if(Valor.equals("")){
        sql= "select id_usuario, Usuario,Contrasenia,id_tipoUsuario from usuario";
        }
        else{
            sql = "select id_usuario,Usuario,Contrasenia,id_tipoUsuario from usuario where  Usuario ='"+Valor+"'";
        }
        String[] datos = new String[4];
        com.mysql.jdbc.Statement st;
        
        
        try{
            ResultSet rs = (ResultSet) conn.Consultar(sql);
            while(rs.next()){
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);

            modelo.addRow(datos);
            }
            jTable1.setModel(modelo);
        } catch(SQLException ex){
            java.util.logging.Logger.getLogger(Usuario.class.getName()) .log(java.util.logging.Level.SEVERE,null,ex);
        }
    }
    public void limpiar(){
        jUsuario.setText("");
        jContrasenia.setText("");
    }
    public Usuario() {
        initComponents();
        mostrardatosTabla(jTextField1.getText());
        jId.setVisible(false);
        jTipoUsuario.addItem("Jefe");
        jTipoUsuario.addItem("Empleado");
        txtTipoUsuario.setVisible(false);
        jButton5.setEnabled(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false); //Quitar maximizar
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE); //Inhabilitar la cruz de cerrar
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jModificar = new javax.swing.JMenuItem();
        jBorrar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTipoUsuario = new javax.swing.JTextField();
        jTipoUsuario = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jId = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jContrasenia = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();

        jPopupMenu1.setComponentPopupMenu(jPopupMenu1);

        jModificar.setText("Modificar");
        jModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jModificarMouseClicked(evt);
            }
        });
        jModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModificarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jModificar);

        jBorrar.setText("Borrar");
        jBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBorrarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jBorrar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevos Usuarios");
        setForeground(java.awt.Color.white);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setComponentPopupMenu(jPopupMenu1);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel1.setText("Usuario:");

        jUsuario.setColumns(15);
        jUsuario.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña:");

        txtTipoUsuario.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        jTipoUsuario.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel4.setText("Tipo Usuario:");

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jId.setEditable(false);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jButton5.setText("Modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jButton3.setText("Buscar usuario");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jContrasenia.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jButton4.setText("Nuevo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton5)
                            .addComponent(jButton4)
                            .addComponent(jButton3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Conectar con = new Conectar();
        Connection cn = (Connection) con.conexion();
        // BOTON GUARDAR
        try{
            if ("".equals(jUsuario.getText())|| "".equals(jContrasenia.getText())){
            JOptionPane.showMessageDialog(null, "Faltan completar campos","Ocurrió un error",JOptionPane.INFORMATION_MESSAGE);  
            }else{
             PreparedStatement pst = (PreparedStatement) cn.prepareStatement("insert into usuario (Usuario,Contrasenia,id_tipoUsuario) values (?,?,?)");
            pst.setString(1,jUsuario.getText()); 
            pst.setString(2,Hash.getHash(jContrasenia.getText(), "SHA1"));
            pst.setString(3,(String) jTipoUsuario.getSelectedItem());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Nuevo usuario creado","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            mostrardatosTabla("");
            limpiar();
            jButton5.setEnabled(false);
            jButton3.setEnabled(true);
            jTextField1.setEnabled(true);
            jButton2.setEnabled(false);
            jButton4.setEnabled(true);
            
            
            }
        } catch (SQLException e){
            java.util.logging.Logger.getLogger(Usuario.class.getName()) .log(java.util.logging.Level.SEVERE,null,e);
            JOptionPane.showMessageDialog(rootPane, e);
            JOptionPane.showMessageDialog(null, "Error SQL Consultar"+e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //mostrardatosTabla(jTextField1.getText());
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModificarActionPerformed
        // TODO add your handling code here:
        jButton5.setEnabled(true);
        jButton3.setEnabled(false);
        jTextField1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton4.setEnabled(false);
        txtTipoUsuario.setVisible(true); // Muestro la caja de texto
        jTipoUsuario.setVisible(false); //Oculto el combobox
        int fila = jTable1.getSelectedRow();
        if(fila>=0){
            jId.setText(jTable1.getValueAt(fila, 0) .toString());
            jUsuario.setText(jTable1.getValueAt(fila, 1) .toString());
            jContrasenia.setText(jTable1.getValueAt(fila, 2) .toString());
            txtTipoUsuario.setText(jTable1.getValueAt(fila, 3).toString());
            
            //Bloquear celdas al modificar y dejar la que se modifica
            
            jContrasenia.setEnabled(false);
            txtTipoUsuario.setEnabled(false);
            

        
        }
        else{
            JOptionPane.showMessageDialog(null,"No seleccionó ninguna fila");
        }
    }//GEN-LAST:event_jModificarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        //AL MODIFICAR UN REGISTRO 
        Conectar con = new Conectar();
        Connection cn = (Connection) con.conexion();
        try{
            String sql = "update usuario set Usuario = '"+jUsuario.getText()+"' where id_usuario = '"+jId.getText()+"'";
            PreparedStatement ps = (PreparedStatement) cn.prepareStatement(sql);
            ps.executeUpdate();
            mostrardatosTabla("");
            limpiar();
            txtTipoUsuario.setVisible(false); // Muestro la caja de texto
            jTipoUsuario.setVisible(true); //Oculto el combobox
            jUsuario.setEnabled(true);
            jContrasenia.setEnabled(true);
            jButton5.setEnabled(false);
            jButton3.setEnabled(true);
            jTextField1.setEnabled(true);
            jButton2.setEnabled(false);
            jButton4.setEnabled(true);
            
            
            
        }catch (SQLException e){
            java.util.logging.Logger.getLogger(Usuario.class.getName()) .log(java.util.logging.Level.SEVERE,null,e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBorrarActionPerformed
        // TODO add your handling code here:
        Conectar con = new Conectar();
        Connection cn = (Connection) con.conexion();
        int fila = jTable1.getSelectedRow();
        int IdUsr = Integer.parseInt(jTable1.getValueAt(fila,0) .toString());
        int confirmar;
        try{
            confirmar = JOptionPane.showConfirmDialog(null,"¿Está seguro que desea borrar el registro?");
            if(JOptionPane.OK_OPTION == confirmar){
            String sql = "delete from usuario where id_usuario = "+IdUsr;
                System.out.println(sql);
            PreparedStatement ps = (PreparedStatement) cn.prepareStatement(sql);
            
            JOptionPane.showMessageDialog(null,"El registro ha sido eliminado exitosamente","Operación Exitosa",JOptionPane.INFORMATION_MESSAGE);
            ps.executeUpdate();
            mostrardatosTabla("");}
            else{JOptionPane.showMessageDialog(null,"Eligió no eliminar el registro","Operación cancelada",JOptionPane.INFORMATION_MESSAGE);
            mostrardatosTabla("");
            }
            
        
        }
        catch(SQLException e){
            java.util.logging.Logger.getLogger(Usuario.class.getName()) .log(java.util.logging.Level.SEVERE,null,e);
        }
    }//GEN-LAST:event_jBorrarActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        buscardatosTabla(jTextField1.getText());
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jModificarMouseClicked
        
    }//GEN-LAST:event_jModificarMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //BOTON NUEVO
        jButton5.setEnabled(false);
        jButton3.setEnabled(false);
        jTextField1.setEnabled(false);
        jButton2.setEnabled(true);
        jButton4.setEnabled(false);

        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>}
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jBorrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPasswordField jContrasenia;
    private javax.swing.JTextField jId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jModificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jTipoUsuario;
    private javax.swing.JTextField jUsuario;
    private javax.swing.JTextField txtTipoUsuario;
    // End of variables declaration//GEN-END:variables
}
